### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by Nagispace** [snailcon/QuadtreeAmogufier#3]

**Comment by Nagispace** [comment]
The program runs  fine until it hits  arround  50 images, and saturates the computer RAM
`terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc`

**Comment by snailcon** [comment]
I have fixed a memory leak  
can you try again and check if it still crashes

**Comment by Nagispace** [comment]
Still crash.
`terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 1555200) >= this->size() (which is 1555200)
      0 [amogus] amogus 1238 cygwin_exception::open_stackdumpfile: Dumping stack trace to amogus.exe.stackdump`
Here is the stackdump also
[amogus.exe.stackdump.txt](https://github.com/snailcon/QuadtreeAmogufier/files/6671664/amogus.exe.stackdump.txt)

**Comment by Nagispace** [comment]
The memory leak is solved and the error I just mentionned only happen when you start  from 0, starting from1 solve the issue
